#!/bin/bash
set -e

path=$(pwd)
git clone https://github.com/openebs/litmus.git
cd litmus/k8s/eks/k8s-installer/

echo "creating cluster"

ansible-playbook create-eks-cluster.yml -vv

mkdir $path/.kube
cat ~/.kube/config > $path/.kube/config
cat ~/.kube/config > $path/.kube/admin.conf
cat ~/logs/clusters > $path/.kube/clusters
cat ~/logs/region > $path/.kube/region

kubectl get nodes
wget https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
kubectl apply -f rbac.yaml
kubectl create configmap kubeconfig --from-file=$path/.kube/admin.conf -n litmus

## Overwrite node hostname label to use FQDN
for i in $(kubectl get nodes -o jsonpath='{.items[*].metadata.name}'); do kubectl label node $i kubernetes.io/hostname=$i --overwrite=true; done

