#!/bin/bash

set -e

#mkdir ~/.aws
#echo $CONFIG > ~/.aws/config
#echo $CREDENTIALS > ~/.aws/credentials

echo "cleanup"
mkdir ~/logs
cp .kube/clusters ~/logs

git clone https://github.com/yudaykiran/litmus.git
git checkout EKSPlatform
cd litmus/k8s/eks/k8s-installer/

echo "cleanup"
ansible-playbook delete-eks-cluster.yml
