#!/bin/bash

set -e

path=$(pwd)
echo "cleanup"
mkdir ~/logs
cp $path/.kube/clusters ~/logs
cp $path/.kube/region ~/logs

git clone https://github.com/openebs/litmus.git
cd litmus/k8s/eks/k8s-installer/

echo "cleanup"
ansible-playbook delete-eks-cluster.yml

